package de.uni.freiburg.iig.telematik.wolfgang.editor.properties;

public enum WolfgangProperty {

	ICON_SIZE,
	
	DEFAULT_PLACE_SIZE,
	DEFAULT_TRANSITION_WIDTH,
	DEFAULT_TRANSITION_HEIGHT,
	DEFAULT_TOKEN_SIZE,
	DEFAULT_TOKEN_DISTANCE,
	
	DEFAULT_VERTICAL_LABEL_OFFSET,
	DEFAULT_HORIZONTAL_LABEL_OFFSET,
	DEFAULT_LABEL_BG_COLOR,
	DEFAULT_LABEL_LINE_COLOR,
	
	DEFAULT_NODE_COLOR,
	DEFAULT_LINE_COLOR,
	DEFAULT_GRADIENT_COLOR,
	DEFAULT_GRADIENT_DIRECTION,

	DEFAULT_FONT_FAMILY,
	DEFAULT_FONT_SIZE,

	DEFAULT_ZOOM_STEP;
}
